export interface AlgerianFoodItem {
  id: string
  name: string
  nameAr: string
  category: 'main' | 'bread' | 'pastry' | 'soup' | 'side'
  calories: number
  protein: number
  carbs: number
  fat: number
  fiber: number
  servingSize: string
  description: string
  imageEmoji: string
}

export const ALGERIAN_FOODS: AlgerianFoodItem[] = [
  {
    id: 'couscous-chicken',
    name: 'Couscous with Chicken & Vegetables',
    nameAr: 'كسكس بالدجاج والخضار',
    category: 'main',
    calories: 580,
    protein: 38,
    carbs: 76,
    fat: 14,
    fiber: 6.5,
    servingSize: '1 medium plate (350g)',
    description: 'Traditional steamed durum wheat semolina with grilled chicken, chickpeas, zucchini, and carrots.',
    imageEmoji: '🍲',
  },
  {
    id: 'rechta-poulet',
    name: 'Rechta with Chicken & Turnips',
    nameAr: 'رشتة بالدجاج واللفت',
    category: 'main',
    calories: 620,
    protein: 42,
    carbs: 82,
    fat: 15,
    fiber: 5.2,
    servingSize: '1 plate (380g)',
    description: 'Artisanal hand-cut thin noodles steamed over white sauce with tender chicken breast and fresh turnips.',
    imageEmoji: '🍜',
  },
  {
    id: 'chakhchoukha-biskra',
    name: 'Chakhchoukha Biskria',
    nameAr: 'شخشوخة بسكرية',
    category: 'main',
    calories: 690,
    protein: 45,
    carbs: 88,
    fat: 18,
    fiber: 7.0,
    servingSize: '1 plate (400g)',
    description: 'Torn thin flatbread shreds simmered in spicy lamb stew with chickpeas and chili peppers.',
    imageEmoji: '🥘',
  },
  {
    id: 'chorba-fririk',
    name: 'Chorba Frik (Green Wheat Soup)',
    nameAr: 'شوربة فريك',
    category: 'soup',
    calories: 280,
    protein: 22,
    carbs: 34,
    fat: 7,
    fiber: 4.8,
    servingSize: '1 large bowl (300ml)',
    description: 'Cracked green wheat soup with lean beef/lamb cubes, cilantro, mint, and lemon juice.',
    imageEmoji: '🥣',
  },
  {
    id: 'garantita',
    name: 'Garantita (Chickpea Cake)',
    nameAr: 'قرنطيطة / كرانطيطة',
    category: 'side',
    calories: 320,
    protein: 16,
    carbs: 42,
    fat: 10,
    fiber: 6.0,
    servingSize: '1 portion (200g)',
    description: 'Roasted chickpea flour bake seasoned with cumin, black pepper, and harissa paste.',
    imageEmoji: '🧆',
  },
  {
    id: 'mahjouba',
    name: 'Mahjouba (Spicy Crepe)',
    nameAr: 'محجوبة',
    category: 'main',
    calories: 390,
    protein: 11,
    carbs: 58,
    fat: 14,
    fiber: 3.5,
    servingSize: '2 large pieces',
    description: 'Thin semolina dough stuffed with caramelized onion, tomato, garlic, and red chili compote.',
    imageEmoji: '🥞',
  },
  {
    id: 'loubia-khadra',
    name: 'Loubia (White Bean Stew)',
    nameAr: 'لوبيا يابسة / بيضاء',
    category: 'main',
    calories: 440,
    protein: 26,
    carbs: 65,
    fat: 9,
    fiber: 12.5,
    servingSize: '1 bowl (350g)',
    description: 'Hearty white bean stew with cumin, tomato sauce, garlic, and optional meat chunks.',
    imageEmoji: '🍲',
  },
  {
    id: 'doubara-biskria',
    name: 'Doubara (Chickpea & Fava Bean Soup)',
    nameAr: 'دوبارة بسكرية',
    category: 'soup',
    calories: 360,
    protein: 20,
    carbs: 54,
    fat: 8,
    fiber: 11.0,
    servingSize: '1 bowl (320g)',
    description: 'Spicy Saharan dish of chickpeas and broad beans soaked in olive oil, harissa, lemon, and cumin.',
    imageEmoji: '🫘',
  },
  {
    id: 'kesra-khobz',
    name: 'Kesra / Khobz El Feghir',
    nameAr: 'كسرة / خبز الفطير',
    category: 'bread',
    calories: 220,
    protein: 6,
    carbs: 42,
    fat: 3.5,
    fiber: 2.8,
    servingSize: '1 quarter flatbread (80g)',
    description: 'Traditional unleavened semolina bread baked on a clay tajine plate.',
    imageEmoji: '🫓',
  },
  {
    id: 'msemen',
    name: 'Msemen',
    nameAr: 'مسمن',
    category: 'pastry',
    calories: 290,
    protein: 7,
    carbs: 45,
    fat: 9.5,
    fiber: 2.0,
    servingSize: '1 square piece (90g)',
    description: 'Square laminated semolina crepe drizzled with natural honey or butter.',
    imageEmoji: '🥐',
  },
  {
    id: 'berkoukes',
    name: 'Berkoukes (Aich)',
    nameAr: 'بركوكش / عيش',
    category: 'main',
    calories: 520,
    protein: 28,
    carbs: 78,
    fat: 11,
    fiber: 5.5,
    servingSize: '1 bowl (380g)',
    description: 'Large hand-rolled pasta pearls simmered in rich vegetable and meat gravy.',
    imageEmoji: '🍲',
  },
  {
    id: 'tajine-zitoun',
    name: 'Tajine Zitoun (Chicken & Green Olives)',
    nameAr: 'طاجين الزيتون',
    category: 'main',
    calories: 490,
    protein: 41,
    carbs: 18,
    fat: 28,
    fiber: 3.8,
    servingSize: '1 dish (320g)',
    description: 'Slow-cooked tender chicken with pitted green olives, mushrooms, and golden onion gravy.',
    imageEmoji: '🫒',
  },
]
